stages:
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git sshpass
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - mkdir -p /root/.ssh
  - echo "$BASTION_PASSWORD" > /root/password.txt
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - ssh-keyscan $BASTION_HOST

deploy_prod:
  stage: deploy
  script:
    - sshpass -f /root/password.txt ssh root@$BASTION_HOST "cat /root/deploy/backend | ssh root@$TARGET_HOST"
  only:
   - master
