stages:
  - build

before_script:
  - apt-get update -qq
  - apt-get install -qq git sshpass
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - mkdir -p /root/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_prod:
  stage: build
  script:
    - mkdir -p /tmp/project
    - docker -v
  only:
   - master
